[config]
version_check = false
reload_apps = true

[config.wallpaper]
command = "swww"
arguments = [
    "img",
    "-t",
    "fade",
    "--transition-duration",
    "0.5",
    "--transition-step",
    "255",
    "--transition-fps",
    "60",
    "-f",
    "Mitchell",
]
set = false

[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true

[templates.debug]
input_path = "~/.config/matugen/templates/colors.json"
output_path = "/tmp/colors.json"

[templates.hyprlandsrc]
input_path = "~/.config/Ax-Shell/config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/hypr/sources/colors.conf"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprlandcolors.sh"
output_path = "/tmp/hyprlandcolors.sh"
post_hook = "sh /tmp/hyprlandcolors.sh"

[templates.hyprlock]
input_path = "~/.config/matugen/templates/hyprland/hyprlock.conf"
output_path = "~/.config/hypr/hyprlock.conf"

[templates.fuzzel]
input_path = "~/.config/matugen/templates/fuzzel/fuzzel_theme.ini"
output_path = "~/.config/fuzzel/fuzzel_theme.ini"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty_theme.conf"
output_path = "~/.config/kitty/current-theme.conf"
post_hook = "pkill -SIGUSR1 kitty"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk/gtk-colors.css"
output_path = "~/.config/gtk-3.0/colors.css"
post_hook = "~/scripts/post-theme-install.sh"
_post_hook = "gsettings set org.gnome.desktop.interface gtk-theme \"\"; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}"

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk/gtk-colors.css"
output_path = "~/.config/gtk-4.0/colors.css"
post_hook = "~/scripts/post-theme-install.sh"

[templates.kde_colors]
input_path = "~/.config/matugen/templates/kde/color.txt"
output_path = "~/.local/state/quickshell/user/generated/color.txt"

[templates.wallpaper]
input_path = "~/.config/matugen/templates/wallpaper.txt"
output_path = "~/.local/state/quickshell/user/generated/wallpaper/path.txt"

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi.config.rasi"
output_path = "~/.config/rofi/config.rasi"

[templates.ashell]
input_path = "~/.config/matugen/templates/ashell.toml"
output_path = "~/.config/ashell/config.toml"

[templates.edges]
input_path = "~/.config/matugen/templates/way-edges.jsonc"
output_path = "~/.config/way-edges/config.jsonc"

[templates.openrgb]
input_path = "~/.config/matugen/templates/openrgb.sh"
output_path = "~/scripts/openrgb.sh"
post_hook = "sh ~/scripts/openrgb.sh"

[templates.znvim]
input_path = "~/.config/matugen/templates/nvim_colors.lua"
output_path = "~/.config/nvim/lua/config/colors.lua"
post_hook = "~/.config/matugen/hooks/nvim.sh"

