[modules]
left = [
    [
        "Updates",
        "SystemInfo",
    ],
    "WindowTitle",
]
center = [
    "Workspaces",
]
right = [
    [
        "Tray",
        "Settings",
    ],
    [
        "Clock",
        "CustomNotifications",
    ],
]

[updates]
check_cmd = "checkupdates; yay -Qua"
update_cmd = "kitty --hold yay -Syu"

[window_title]
mode = "Class"
truncate_title_after_length = 75

[appearance]
_style = "Gradient"
primary_color = "#ffb1c2"
success_color = "#ecbe91"
text_color = "#ffb1c2"
workspace_colors = [
    "#8a8bf1",
    "#e5c890",
    "#a6d189",
    "#e78284",
]
opacity = 1.0

[appearance.menu]
opacity = 0.8

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.background_color]
base = "#713343"
strong = "#9e8c8f"
weak = "#8d4a5a"

[appearance.secondary_color]
base = "#5b3f45"

[settings]
lock_cmd = "hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "adw-bluetooth || blueman-manager"
remove_airplane_btn = true

[workspaces]
enable_workspace_filling = false
max_workspaces = 10
disable_special_workspaces = true

[[CustomModule]]
name = "CustomNotifications"
icon = ""
command = "swaync-client -t -sw"
listen_cmd = "swaync-client -swb"
alert = ".*notification"

[CustomModule.icons]
"dnd.*" = ""

