[pyprland]
plugins = [
    "layout_center",
]

[layout_center]
margin = 60
offset = [
    0,
    30,
]
next = "movefocus r"
prev = "movefocus l"
next2 = "movefocus d"
prev2 = "movefocus u"
style = [
    "bordercolor rgb(ec8800)",
    "bordersize 3",
    "dimaround",
]

