[pyprland]
plugins = [
    "layout_center",
]

[layout_center]
margin = 60
offset = [
    0,
    30,
]
next = "movefocus r"
prev = "movefocus l"
next2 = "movefocus d"
prev2 = "movefocus u"
style = [
    "border_color rgb(ec8800)",
    "border_size 3",
    "dim_around yes",
]

