[pyprland]
plugins = [
    "scratchpads",
]

[scratchpads.filemanager]
animation = "fromLeft"
command = "uwsm-app -- nemo --name nemo-pad"
class = "nemo-pad"
margin = 100
pinned = false
size = "50% 80%"

[scratchpads.stb]
animation = "fromBottom"
command = "[term_classed] term-stb ~/scripts/sstb"
class = "term-stb"
size = "75% 45%"

[scratchpads.stblogs]
animation = "fromTop"
command = "[term_classed] term-stb-logs ~/scripts/stbLog"
class = "term-stb-logs"
lazy = false
size = "75% 40%"

[scratchpads.term]
animation = "fromTop"
command = "[term_classed] main-dropterm"
class = "main-dropterm"
size = "75% 60%"
max_size = "1920px 100%"

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
size = "40% 90%"
max_size = "1080px 100%"
unfocus = "hide"

[scratchpads.volume.per_monitor]
DELL = [
    { animation = "fromLeft", size = "40% 90%", position = "10% 10%" },
]

